### ISSUE TITLE
Unknown registry key: draconicadditions:harnessvoid

### ISSUE THREAD

**Issue by LevelsCraft7** [FoxMcloud5655/Draconic-Additions#55] opened 2022-07-27 19:24 UTC
Hello,

I have a problem with "draconicadditions:harnessvoid".
No matter the version of the mod or forge, the server crashes constantly because of this error.

Attached: the message in question. 
`[main/FATAL] [net.minecraft.server.Main/]: Failed to start the minecraft server
java.lang.RuntimeException: Unknown registry key: draconicadditions:harnessvoid
	at com.mojang.serialization.DataResult.lambda$getOrThrow$4(DataResult.java:100) ~[?:?]
	at com.mojang.datafixers.util.Either$Right.map(Either.java:99) ~[?:?]
	at com.mojang.serialization.DataResult.getOrThrow(DataResult.java:93) ~[?:?]
	at net.minecraft.server.Main.main(Main.java:153) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_301]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_301]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_301]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_301]
	at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:37) ~[forge-1.16.5-36.2.39.jar:36.2]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?]
	at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:49) [forge-1.16.5-36.2.39.jar:?]
	at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:46) [forge-1.16.5-36.2.39.jar:?]
	at net.minecraftforge.server.ServerMain.main(ServerMain.java:43) [forge-1.16.5-36.2.39.jar:?]`

Thanks

**Comment by FoxMcloud5655** [comment] 2022-07-28 03:51
First, make sure that you're running the latest version (2.2.2.5 at the time of this post).  Secondly, make sure this happens in a new world as well.  Finally, please post the full log, not a shortened one.

**Comment by FoxMcloud5655** [comment] 2022-07-28 19:30
Duplicate of #53.

**Closed as not planned by FoxMcloud5655** 2022-07-28 19:30 UTC

**Comment by LevelsCraft7** [comment] 2022-07-28 19:41
I have tried with all the latest updates and the last two versions of forge and I always end up with the same result

**Comment by LevelsCraft7** [comment] 2022-07-28 19:45
2.1.0.2 is the version that has the least problems and seems to be more compatible with the other modes
